# Generated by Django 4.1.4 on 2023-01-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.TextField(default='2023-01-26'),
            preserve_default=False,
        ),
    ]
